[PR1] DEV-55 Added Transmit Table
HyperloopUPV-H8/Frontend-H8 pull request #10
Opened 2022-11-27 16:05 UTC by smorsua

This PR adds the transmit table, which is used to send orders to the vehicle. It currently supports checkbox for the boolean values and input for the numeric values. Dropdowns will be added in the future to support enums. Input verification will be added in the future.

[screen-capture (5).webm](https://user-images.githubusercontent.com/114338434/204144997-cc184305-d199-4358-809d-48102ace9cc6.webm)

2022-11-28 19:16 UTC, jmaralo requested changes
There is just one main thing that I found, the rest are just my opinion

2022-11-28 19:16 UTC, jmaralo commented on src/components/PacketTable/TransmitTable/OrderField.tsx
> +    case "boolean":
this should be just bool

2022-11-28 19:16 UTC, jmaralo commented on src/components/PacketTable/TransmitTable/OrderField.tsx
> +    case "float64":
this is hard to follow (but we can't avoid it), what I did in the backend was to have all numeric cases as the default case, but this also works

2022-11-28 19:16 UTC, jmaralo commented on src/components/PacketTable/TransmitTable/OrderFields.tsx
> +                //FIXME: que sea mas obvio que la id es el name de la orden o hacerlo de otra manera mas explicita
we should try to avoid other languages, even in code (but this is more a personal preference)

2022-11-29 17:48 UTC, jmaralo approved these changes

2022-11-29 21:29 UTC, lipezaballa commented on src/components/PacketTable/TransmitTable/OrderFields.tsx
> +                //FIXME: make it more obvious that the id is the name of the order or do it another way
I would like to add some comments to my code for future improvements, is this the way to do it?

2022-11-29 22:22 UTC, lipezaballa commented on src/components/PacketTable/TransmitTable/TransmitTable.tsx
> +    return (fields: FieldState[]) => {
Which is the function of the fieldstate?

2022-11-29 22:46 UTC, lipezaballa commented on src/styles/globalOverride.scss
> +@use "@styles/styles";
we'll have to fix it with my override methods

2022-11-29 22:47 UTC, lipezaballa approved these changes

2022-11-30 15:31 UTC, merged